version: '3'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  auth-service:
    build: ./auth-service
    volumes:
      - ./auth-service/src:/usr/src/app/src
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - '3001:3001'
    depends_on:
      - redis

  notification-service:
    build: ./notification-service
    volumes:
      - ./notification-service/src:/usr/src/app/src
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - '3002:3002'
    depends_on:
      - redis

  product-service:
    build: ./product-service
    volumes:
      - ./product-service/src:/usr/src/app/src
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - '3003:3003'
    depends_on:
      - redis
